#modLoader = "javafml"
#loaderVersion = "[43,)"

modLoader="kotlinforforge"
loaderVersion="[3,)"
#issueTrackerURL = ""
license = "LGPLv3"

[[mods]]
modId = "thaumcraft"
version = "${version}"
displayName = "Kenza's Thaumcraft"
authors = "Kenza"
description = '''
Desc test.
'''
#logoFile = ""

[[dependencies.thaumcraft]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.thaumcraft]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.thaumcraft]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thaumcraft]]
modId = "geckolib3"
mandatory = true
versionRange = "[3.1.30,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thaumcraft]]
modId = "byg"
mandatory = true
versionRange = "[2.0.0.13,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thaumcraft]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"

